### ISSUE TITLE
`assign_attributes': undefined method `iso8601' for Time:Class (NoMethodError)

### ISSUE THREAD

**Issue by PortEdison** [will-in-wi/letsencrypt-webfaction#41] opened 2016-08-17 23:31 UTC
Hey, using the latest version I was getting an the error `/home/.../.letsencrypt_webfaction/gems/gems/acme-client-0.4.0/lib/acme/client/resources/authorization.rb:28:in `assign_attributes': undefined method `iso8601' for Time:Class (NoMethodError)` when trying to run letsencrypt_webfaction command, when I rolled back to -v 1.1.0 I ended up at the error Failed to verify statuses in 10 seconds on your troubleshooting page which I then resolved by redirecting http to https.

**Comment by will-in-wi** [comment] 2016-08-18 12:44
This is a duplicate of https://github.com/will-in-wi/letsencrypt-webfaction/issues/39 which is fixed in 1.1.7, just released a few minutes ago.

Thanks for reporting!

**Closed by will-in-wi** 2016-08-18 12:44 UTC
